[debug] [2019-03-02T16:11:09.020Z] ----------------------------------------------------------------------
[debug] [2019-03-02T16:11:09.023Z] Command:       C:\Program Files (x86)\nodejs\node.exe D:\Pramod_2nd\Projects\ReusableComponents\node_modules\firebase-tools\lib\bin\firebase.js use reuablecomponent
[debug] [2019-03-02T16:11:09.023Z] CLI Version:   6.4.0
[debug] [2019-03-02T16:11:09.023Z] Platform:      win32
[debug] [2019-03-02T16:11:09.024Z] Node Version:  v6.11.1
[debug] [2019-03-02T16:11:09.024Z] Time:          Sat Mar 02 2019 21:41:09 GMT+0530 (India Standard Time)
[debug] [2019-03-02T16:11:09.024Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-03-02T16:11:09.039Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-03-02T16:11:09.039Z] > authorizing via signed-in user
[debug] [2019-03-02T16:11:09.042Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects  
 
[debug] [2019-03-02T16:11:10.452Z] <<< HTTP RESPONSE 200
[debug] [2019-03-02T16:11:10.729Z] Error: EBUSY: resource busy or locked, rename 'C:\Users\manu\.config\configstore\firebase-tools.json.2674469665' -> 'C:\Users\manu\.config\configstore\firebase-tools.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:810:18)
    at Function.writeFileSync [as sync] (D:\Pramod_2nd\Projects\ReusableComponents\node_modules\configstore\node_modules\write-file-atomic\index.js:124:8)
    at Object.set (D:\Pramod_2nd\Projects\ReusableComponents\node_modules\configstore\index.js:62:21)
    at Object.Configstore.set (D:\Pramod_2nd\Projects\ReusableComponents\node_modules\configstore\index.js:93:11)
    at Object.makeActiveProject (D:\Pramod_2nd\Projects\ReusableComponents\node_modules\firebase-tools\lib\utils.js:110:17)
    at D:\Pramod_2nd\Projects\ReusableComponents\node_modules\firebase-tools\lib\commands\use.js:68:23
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
[error] 
[error] Error: An unexpected error has occurred.
